language: android
android:
  components:
    - tools
    - platform-tools
    - tools

    # BuildTools version used in project
    - build-tools-26.0.2

    # SDK version used to compile project
    - android-25
